version: "3"
services:
   superalgos-docker-dev:
      build:
         context: .
         dockerfile: ./Dockerfile
      environment:
        - BRANCH=${BRANCH:-develop}
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_EMAIL_ADRESS=${GIT_EMAIL_ADRESS}
        - GIT_PERSONAL_ACCESS_TOKEN=${GIT_PERSONAL_ACCESS_TOKEN}

      image: 'docker-superalgos-develop:develop' 
      container_name: Superalgos-Develop
      network_mode: bridge
      ports:
        - '34248:34248' 
        - '18041:18041'
      volumes:
        - "${VOLUME_MOUNT_LOCAL_-./src}:${VOLUME_MOUNT_CONTAINER:-/app}"
